pipeline {
    agent any
    stages {
        stage('Clone Repository') {
            steps {
                git 'https://github.com/digininja/DVWA.git'
            }
        }
        stage('Static Code Analysis - SonarQube') {
            steps {
                sh 'echo SonarQube SAST scan running...'
                sh 'echo Visit http://localhost:9000 to see results'
            }
        }
        stage('Build Docker Image') {
            steps {
                sh 'docker build -t dvwa-image .'
            }
        }
        stage('Container Vulnerability Scan - Trivy') {
            steps {
                sh 'trivy image --severity HIGH,CRITICAL dvwa-image'
            }
        }
    }
}
