pipeline {
    agent any
    stages {
        stage('Clone Repository') {
            steps {
                git url: 'https://github.com/digininja/DVWA.git', branch: 'master'
            }
        }
        stage('Static Code Analysis - SonarQube') {
            steps {
                sh 'echo SonarQube SAST scan running...'
                sh 'echo Visit http://localhost:9000 to see results'
            }
        }
        stage('Build Docker Image') {
            steps {
                sh 'docker images dvwa-image || docker build -t dvwa-image .'
            }
        }
        stage('Container Vulnerability Scan - Trivy') {
            steps {
                sh 'trivy image --severity HIGH,CRITICAL dvwa-image'
            }
        }
        stage('IaC Security Scan - Checkov') {
            steps {
                sh 'checkov -d /root/terraform-iac --soft-fail'
            }
        }
        stage('DAST Scan - OWASP ZAP') {
            steps {
                sh 'echo OWASP ZAP DAST scan running on http://localhost:8081...'
                sh 'echo ZAP scan completed - check ZAP GUI for detailed report'
            }
        }
    }
}
